name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  nix-build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check
    - run: nix bundle --bundler github:NixOS/bundlers .#
    - uses: softprops/action-gh-release@v1
      with:
        files: panimacs-arx
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
