name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  nix-build-and-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "write"
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main
    - run: nix bundle --bundler github:NixOS/bundlers .#
    - uses: softprops/action-gh-release@v2
      with:
        files: panimacs-arx
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
